name: Blank Issue
description: Create an issue with minimal structure (for experienced authors)
body:
  - type: markdown
    attributes:
      value: |
        This is a minimal template for experienced docs authors and developers who prefer to structure their own issues.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue
      placeholder: What's the issue?
    validations:
      required: true
