#blank_issues_enabled: true
contact_links:
  - name: ALCF Users Slack Workspace
    url: https://alcf-users.slack.com/
    about: User community for discussion, collaboration, and assistance. This pilot program is only open to select users, see [here](https://docs.alcf.anl.gov/contacting-support/alcf-users-slack/) for details
  - name: ALCF Support (Open a Ticket)
    url: mailto:support@alcf.anl.gov
    about: For technical user support issues or questions after reading the user-guides, our ALCF Support team is available from 9 a.m. to 5 p.m. Central Time, Monday - Friday, except on holidays.
  - name: ALCF Service Desk (Accounts Issues)
    url: mailto:accounts@alcf.anl.gov
    about: Contact ALCF support directly for account-related questions.
  - name: ALCF Homepage
    url: https://www.alcf.anl.gov/
  - name: MyALCF Account Management
    url: https://my.alcf.anl.gov/
    about: For self-management of ALCF account, allocations, and project membership.
  - name: ALCF User Guides
    url: https://docs.alcf.anl.gov/
    about: Check the official documentation first to see if your question is already answered.
